filebeat.inputs:
- type: filestream
  paths: 
    - '/logs/*.log'

processors:
- decode_json_fields:
    fields: ["message"]
    target: "x"
    process_array: true

- replace:
    fields:
      - field: "log.file.path"
        pattern: "/logs/"
        replacement: ""
      - field: "log.file.path"
        pattern: ".log"
        replacement: ""
    ignore_missing: false
    fail_on_error: false

- drop_fields:
    fields:
      - "/agent.*/"
    ignore_missing: true

output.elasticsearch:
  hosts: ${ELASTICSEARCH_HOSTS}
  indices:
    - index: "pm2-%{[log.file.path]}-%{+yyyy.MM.dd}"